name: Build and Deploy WASM

on:
  push:
    branches:
      - main  # main ブランチに push で自動デプロイ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # emsdk をセットアップ
    - name: Setup Emscripten
      uses: emscripten-core/setup-emsdk@v1
      with:
        version: latest

    - name: Compile C to WASM
      run: |
        emcc sine_test.c -O3 \
          -s WASM=1 \
          -s EXPORTED_FUNCTIONS="['_generate_sine','_free_buffer']" \
          -s EXPORTED_RUNTIME_METHODS="['cwrap','getValu]()
